### ISSUE TITLE
Automatically (and optionally) changing the branch name on git(hub|lab)?

### ISSUE THREAD

**Issue by combinatorist** [SixArm/git-rename-master-branch-to-main#2]
I am updating the project name on github so far. Want to talk about merging out work: https://github.com/combinatorist/rename-default-git-branch?

I'm happy to fork yours if our goals are explicit and aligned.

**Comment by joelparkerhenderson** [comment]
Thanks! Yes please. For GitHub, this is the tool that we're using: https://www.npmjs.com/package/github-default-branch

I added a GitHub API function. Want to take a look at it now? If you want to edit it, or add others such as GitLab or Bitbucket, that would be excellent! Thanks.

**Comment by joelparkerhenderson** [comment]
I added a GitHub API function. Want to take a look at it now? If you want to edit it, or add others such as GitLab or Bitbucket, that would be excellent! Thanks.

**Comment by combinatorist** [comment]
It looks like github (and git itself) have committed to the slow process of
switching the default branch name to main or something configurable, so I
think I'm going to stop working on my repo and possibly archive it soon,
but happy to jump back into it they every reverse course.
